apiVersion: v1
kind: Pod
metadata:
  name: nginx # Pod Name
  labels:
    project: roboshop
    environment: dev
    purpose: poc
spec:
  containers:
  - name: nginx # Container Name
    image: nginx # By default it will get from docker hub
  nodeSelector:
    project: roboshop